"""Removendo quantidade_totalal de estoque

Revision ID: 1bb1a1431ec2
Revises: 5dff0c55cfdd
Create Date: 2025-02-25 00:30:22.129620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb1a1431ec2'
down_revision = '5dff0c55cfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tab_estoque', schema=None) as batch_op:
        batch_op.drop_column('quantidade_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tab_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_total', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
