"""Removendo id_estoque em doação

Revision ID: 237fc9bc00c6
Revises: 2d9a7f1ba494
Create Date: 2025-02-25 05:13:40.733533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237fc9bc00c6'
down_revision = '2d9a7f1ba494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tab_doacao', schema=None) as batch_op:
        batch_op.drop_column('estoque_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tab_doacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estoque_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
