"""Atualizando tipo da foto do animal

Revision ID: 488077723664
Revises: 88a5e96f3116
Create Date: 2025-02-25 00:27:19.195477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488077723664'
down_revision = '88a5e96f3116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tab_animal', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tab_animal', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
