"""Init

Revision ID: 5dff0c55cfdd
Revises: 
Create Date: 2025-02-22 17:13:45.769007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dff0c55cfdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_adocao',
    sa.Column('adocao_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('adotante_id', sa.Integer(), nullable=False),
    sa.Column('companha_id', sa.Integer(), nullable=False),
    sa.Column('data_devolucao', sa.String(), nullable=False),
    sa.Column('motivo_devolucao', sa.String(), nullable=False),
    sa.Column('data_adocao', sa.String(), nullable=False),
    sa.Column('data_cadastro', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('adocao_id')
    )
    op.create_table('tab_adotante',
    sa.Column('adotante_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('moradia', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('adotante_id')
    )
    op.create_table('tab_animal',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('idade', sa.String(), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('sexo', sa.String(), nullable=False),
    sa.Column('castracao', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('especie', sa.String(), nullable=False),
    sa.Column('data_cadastro', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('animal_id')
    )
    op.create_table('tab_apadrinhamento',
    sa.Column('apadrinhamento_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('nome_apadrinhador', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('regularidade', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('apadrinhamento_id')
    )
    op.create_table('tab_campanha',
    sa.Column('campanha_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.String(), nullable=False),
    sa.Column('data_termino', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('local', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('campanha_id')
    )
    op.create_table('tab_despesa',
    sa.Column('despesa_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('data_despesa', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('procedimento_id', sa.Integer(), nullable=False),
    sa.Column('comprovante', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('despesa_id')
    )
    op.create_table('tab_doacao',
    sa.Column('doacao_id', sa.Integer(), nullable=False),
    sa.Column('doador', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('data_doacao', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('companha_id', sa.Integer(), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('comprovante', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('doacao_id')
    )
    op.create_table('tab_estoque',
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('tipo_item', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('especie_animal', sa.String(), nullable=False),
    sa.Column('quantidade', sa.String(), nullable=False),
    sa.Column('quantidade_total', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('estoque_id')
    )
    op.create_table('tab_hospedeiro',
    sa.Column('hospedeiro_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('moradia', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('hospedeiro_id')
    )
    op.create_table('tab_lar_temporario',
    sa.Column('lar_temporario_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('hospedeiro_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('data_hospedagem', sa.String(), nullable=False),
    sa.Column('data_cadastro', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('lar_temporario_id')
    )
    op.create_table('tab_procedimento',
    sa.Column('procedimento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('data_procedimento', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('voluntario_id', sa.Integer(), nullable=False),
    sa.Column('despesa_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('procedimento_id')
    )
    op.create_table('tab_tarefa',
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data_tarefa', sa.String(), nullable=False),
    sa.Column('voluntario_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tarefa_id')
    )
    op.create_table('tab_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tab_voluntario',
    sa.Column('voluntario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('voluntario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_voluntario')
    op.drop_table('tab_user')
    op.drop_table('tab_tarefa')
    op.drop_table('tab_procedimento')
    op.drop_table('tab_lar_temporario')
    op.drop_table('tab_hospedeiro')
    op.drop_table('tab_estoque')
    op.drop_table('tab_doacao')
    op.drop_table('tab_despesa')
    op.drop_table('tab_campanha')
    op.drop_table('tab_apadrinhamento')
    op.drop_table('tab_animal')
    op.drop_table('tab_adotante')
    op.drop_table('tab_adocao')
    # ### end Alembic commands ###
