"""Removendo id_despesa em procedimento

Revision ID: 77e8e1eacf24
Revises: 237fc9bc00c6
Create Date: 2025-02-25 06:57:37.949610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e8e1eacf24'
down_revision = '237fc9bc00c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tab_procedimento', schema=None) as batch_op:
        batch_op.drop_column('despesa_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tab_procedimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('despesa_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
