"""Init

Revision ID: 7e1b296a40b9
Revises: 
Create Date: 2025-01-28 09:02:56.957810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1b296a40b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_entity',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('attr1', sa.String(), nullable=False),
    sa.Column('attr2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tab_entity')
    # ### end Alembic commands ###
