"""Adiciona modelo Animal

Revision ID: f04912df57df
Revises: 7e1b296a40b9
Create Date: 2025-01-28 09:20:06.825107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04912df57df'
down_revision = '7e1b296a40b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_animal',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('idade', sa.String(), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('sexo', sa.String(), nullable=False),
    sa.Column('castracao', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('especie', sa.String(), nullable=False),
    sa.Column('data_cadastro', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('animal_id')
    )
    op.drop_table('tab_entity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_entity',
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('attr1', sa.VARCHAR(), nullable=False),
    sa.Column('attr2', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.drop_table('tab_animal')
    # ### end Alembic commands ###
